# Generated by Django 5.2.6 on 2025-09-30 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=100)),
                ("required_level", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=300)),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="General", max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        default=30,
                        help_text="Duration in minutes",
                        null=True,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("difficulty", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProgramWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("title", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("tips", models.TextField(blank=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="extras.program",
                    ),
                ),
            ],
            options={
                "ordering": ["week_number"],
                "unique_together": {("program", "week_number")},
            },
        ),
        migrations.CreateModel(
            name="WeekActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("practice", "Practice Test"),
                            ("writing", "Writing Task"),
                            ("flashcard", "Flashcard Set"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "flashcard_sets",
                    models.ManyToManyField(blank=True, to="myapp.flashcardset"),
                ),
                (
                    "practice_tests",
                    models.ManyToManyField(blank=True, to="myapp.practicetest"),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="extras.programweek",
                    ),
                ),
                (
                    "writing_tasks",
                    models.ManyToManyField(blank=True, to="myapp.writingtask"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_earned", models.DateTimeField(auto_now_add=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="extras.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "achievement")},
            },
        ),
    ]
