# Generated by Django 5.2.6 on 2025-10-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0002_alter_programweek_options_activity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="program",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="program",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="program",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="program",
            name="owner",
        ),
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="subject",
            field=models.TextField(blank=True, default="General"),
        ),
    ]
