# Generated by Django 5.2.6 on 2025-10-04 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_username_onboarding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
    ]
