# Generated by Django 5.2.6 on 2025-10-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_profile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="goals",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of user's goals/interests",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="referral_other",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="referral_source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
