# Generated by Django 5.2.6 on 2025-10-14 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_customuser_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["price"]},
        ),
        migrations.AlterModelOptions(
            name="usersubscription",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.TextField(
                blank=True, help_text="JSON list of features", null=True
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="goals",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
