# Generated by Django 5.2.6 on 2025-10-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_subscriptionplan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="non_features",
            field=models.TextField(
                blank=True,
                help_text="List of non-features e.g 'No priority support'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="List of features separated by comments e.g.",
                null=True,
            ),
        ),
    ]
