# Generated by Django 5.2.6 on 2025-10-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_remove_practicetestresult_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="writingtaskresult",
            name="feedback",
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
