# Generated by Django 5.2.6 on 2025-10-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_writingtaskresult_feedback"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flashcardsetprogress",
            old_name="user",
            new_name="owner",
        ),
    ]
