# Generated by Django 5.2.6 on 2025-10-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_user_flashcardsetprogress_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardsetprogress",
            name="last_reviewed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
